<?php $addUrl = $this->url('zfcadmin/lwccmscontent', array(
    'action'=>'form',
    'type' => $type
)); ?>
<a class="pull-right btn btn-primary btn-edit" href="<?php echo $addUrl; ?>">
    Add content
</a>
<table class="table table-striped">
    <thead>
        <tr>
            <th width="5%">ID</th>
            <th width="70%">Name</th>
            <th width="10%">Visible</th>
            <th width="15%">Actions</th>
        </tr>
    </thead>
    <?php foreach($items as $item) : ?>
        <?php $content = $service->getContentByBaseObject($item); ?>
        <?php $editUrl = $this->url('zfcadmin/lwccmscontent', array(
            'action' => 'form',
            'type' => $type,
            'id' => $content->getId()
        )); ?>
        <?php $deleteUrl = $this->url('zfcadmin/lwccmscontent', array(
            'action' => 'delete',
            'id' => $content->getId()
        )); ?>
        <tr>
            <td><?php echo $content->getId(); ?></td>
            <td><?php echo $this->escapehtml($content); ?></td>
            <td><?php echo $content->getVisible() == 1 ? 'yes' : 'no'; ?></td>
            <td>
                <div class="btn-group">
                    <a href="<?php echo $editUrl; ?>" class="btn btn-primary btn-xs btn-edit">Edit</a>
                    <a href="<?php echo $deleteUrl; ?>" class="btn btn-danger btn-xs">Delete</a>
                </div>
            </td>
        </tr>
    <?php endforeach; ?>
</table>