<article class="<?php echo $article->getWeight()?>u">
    <?php if($article->getHeaderText()) : ?>
        <?php echo $this->contentHeader($article); ?>
    <?php endif; ?>
    <?php if($article->getImagePath()) : ?>
        <?php echo $this->contentImage($article); ?>
    <?php endif; ?>
    <?php if($body = $article->getBody()) : ?>
        <p><?php echo $body; ?></p>
    <?php endif; ?>
</article>

