<section class="<?php echo $section->getWeight()?>u">
    <?php if($section->getHeaderText()) : ?>
        <?php echo $this->contentHeader($section); ?>
    <?php endif; ?>
    <?php if($section->getImagePath()) : ?>
        <?php echo $this->contentImage($section); ?>
    <?php endif; ?>
    <?php if($body = $section->getBody()) : ?>
        <p><?php echo $body; ?></p>
    <?php endif; ?>
</section>